{% set name = "opentelemetry-sdk" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_sdk-{{ version }}.tar.gz
  sha256: cd3230930a2ab288b1df149d261e9cd2bd48dee54ad18465a777831cb6779e90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ==1.18.0
    - opentelemetry-semantic-conventions ==0.39b0
    - setuptools >=16.0
    - typing-extensions >=3.7.4
    # - typing_extensions >=3.7.4

test:
  imports:
    - opentelemetry.sdk
    - opentelemetry.sdk.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/measter/opentelemetry-sdk
  summary: OpenTelemetry Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
