{% set name = "opentelemetry-sdk" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_sdk-{{ version }}.tar.gz
  sha256: 9ddf60195837b59e72fd2033d6a47e2b59a0f74f0ec37d89387d89e3da8cab7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - opentelemetry-api =={{ version }}
    - opentelemetry-semantic-conventions ==0.44b0
    - typing-extensions >=3.7.4
    # - typing_extensions >=3.7.4
    # - typing_extensions >=3.7.4
    # - typing_extensions >=3.7.4
    # - typing_extensions >=3.7.4

test:
  imports:
    - opentelemetry.sdk
    - opentelemetry.sdk.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-sdk
  summary: OpenTelemetry Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
    - conda-forgeopentelemetry-semantic-conventions
