{% set name = "opentelemetry-sdk" %}
{% set version = "1.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_sdk-{{ version }}.tar.gz
  sha256: 45267ac1f38a431fc2eb5d6e0c0d83afc0b78de57ac345488aa58c28c17991d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api =={{ version }}
    - opentelemetry-semantic-conventions ==0.43b0
    - typing-extensions >=3.7.4
    # - typing_extensions >=3.7.4
    # - typing_extensions >=3.7.4
    # - typing_extensions >=3.7.4
    # - typing_extensions >=3.7.4

test:
  imports:
    - opentelemetry.sdk
    - opentelemetry.sdk.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-sdk
  summary: OpenTelemetry Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
