{% set name = "opentelemetry-sdk" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_sdk-{{ version }}.tar.gz
  sha256: 702e432a457fa717fd2ddfd30640180e69938f85bb7fec3e479f85f61c1843f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ==1.20.0
    - opentelemetry-semantic-conventions ==0.41b0
    - setuptools >=16.0
    - typing-extensions >=3.7.4
    # - typing_extensions >=3.7.4
    # - typing_extensions >=3.7.4
    # - typing_extensions >=3.7.4

test:
  imports:
    - opentelemetry.sdk
    - opentelemetry.sdk.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/measter/opentelemetry-sdk
  summary: OpenTelemetry Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
