conda_forge_output_validation: true
bot:
  automerge: true
  check_solvable: true
  run_deps_from_wheel: true
  inspection: update-grayskull
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
